### ISSUE TITLE
Rank File Corrupting and Disabling Functions

### ISSUE THREAD

**Issue by acabral08** [Xandaros/evolve#119]
On a server a friend of mine and I manage, we have been running Evolve for three years. Recently we have run into an issue where there are no console errors related to Evolve as far as I can see, but players spawn without anything, the commands all fail to work, the scoreboard won't show, and users have no rank. When I deleted the ev_userranks file, the issue went away until the next server restart when it occurred again. I tried this process again, and the same thing happened. I don't know if Evolve is corrupting its rank file while the server is running, but this is a major problem.

Here are some Evolve related errors I caught in console:
Failed to load custom font file 'c:/program files (x86)/steam/steamapps/common/garrysmod/garrysmod/resource/fonts/slippy.ttf'
[ACF] ACF Is Up To Date, Latest Version: 529
Hook 'PlayerSpawn' in plugin 'Player Info' failed with error:
Physgun build mode is available on this server

Unknown command: evolve_startmotd

**Comment by MattJeanes** [comment]
Just an FYI, this is fixed by your localisation of vON. I had the same issue in my version of evolve too and localising it fixed it. You can safely close it.

**Comment by Xandaros** [comment]
Well, I also updated vON, but fixing that issue was the whole point. Thanks for the feedback.
