### ISSUE TITLE
evs doesn't work

### ISSUE THREAD

**Issue by Blitzoreo** [Xandaros/evolve#120]
Started this one again because everyone misunderstood this.

evs works, but not as intended. I KNOW it is a console command.

When I type something like "evs explode BlitzOreo" in the console, I explode but I also get a message implying that I exploded myself. I remember "evs" acting the same as the chat command "@", so no message appears.

That's why I'm wondering if this is actually an issue or the "silent command" feature got removed. If so, can I add it back somehow?

**Comment by Xandaros** [comment]
Fixed in 3c71fde9ea769aaf9a1decc040a8961cb5015991
