### ISSUE TITLE
SVN not working

### ISSUE THREAD

**Issue by doxlulzem** [Xandaros/evolve#124]
Whenever I try to use Evolve SVN on my server, it will come up with things such as this
"[EV] Hook 'PlayerSpawn' in plugin 'Player Info' failed with error:

[ERROR] addons/evolve/lua/ev_framework.lua:109: attempt to call method 'Log' (a nil value)
  1. Notify - addons/evolve/lua/ev_framework.lua:109
   2. unknown - addons/evolve/lua/ev_framework.lua:280

[ERROR] addons/evolve/lua/ev_plugins/sv_playerinfo.lua:85: attempt to call method 'GetProperty' (a nil value)
  1. unknown - addons/evolve/lua/ev_plugins/sv_playerinfo.lua:85

Timer Failed! [EV_PlayTimeSave][@addons/evolve/lua/ev_plugins/sv_playerinfo.lua (line 82)]
[EV] Hook 'PlayerGiveSWEP' in plugin 'Restriction' failed with error:

[ERROR] addons/evolve/lua/ev_framework.lua:109: attempt to call method 'Log' (a nil value)
  1. Notify - addons/evolve/lua/ev_framework.lua:109
   2. Call - addons/evolve/lua/ev_framework.lua:280
    3. unknown - gamemodes/sandbox/gamemode/commands.lua:705
     4. unknown - lua/includes/modules/concommand.lua:69"

The Evolve addon in the workshop kinda works (albeit buggy) but I cannot get the SVN working. I've checked and it seems like all the .lua files are there, and I'm clueless. Anything that might be a problem? I installed the trunk with TortoiseSVN into my server's garrysmod\addons directory. Is that it?

**Comment by Xandaros** [comment]
Hmm, those are very strange errors you are getting...
I don't think it has anything to do with SVN, but have you tried downloading evolve as a [zip](https://github.com/Xandaros/evolve/archive/master.zip) and extracting it?

**Comment by doxlulzem** [comment]
I did try to do that and it didn't work. I also tried putting the .lua files into the server's lua directory. Alas nothing happened

**Comment by Xandaros** [comment]
Well, whatever the case, there must be an underlying error. Try and see if there are any different error messages. There should be at least one before the ones complaining about Log not existing.

**Comment by doxlulzem** [comment]
This reply was far too late and I'm dreadfully sorry about it. Right. Here is the exact error message before I even do anything:
"Client "Kurisu Makise" connected (82.21.81.107:27006).

[ERROR] addons/evolve/lua/ev_framework.lua:428: attempt to index field 'von' (a nil value)
  1. SavePlayerInfo - addons/evolve/lua/ev_framework.lua:428
   2. CommitProperties - addons/evolve/lua/ev_framework.lua:499
    3. unknown - addons/evolve/lua/ev_plugins/sv_playerinfo.lua:103

Timer Failed! [EV_PlayTimeSave][@addons/evolve/lua/ev_plugins/sv_playerinfo.lua (line 82)]
[EV] Hook 'PlayerSpawn' in plugin 'Player Info' failed with error:

[ERROR] addons/evolve/lua/ev_framework.lua:116: attempt to call method 'Log' (a nil value)
  1. Notify - addons/evolve/lua/ev_framework.lua:116
   2. unknown - addons/evolve/lua/ev_framework.lua:287"

**Comment by doxlulzem** [comment]
I also attempted to set a rank (It was a new server) to myself, and this is that error message:
"ev rank Kurisu owner

[ERROR] addons/evolve/lua/ev_plugins/sv_consolecommands.lua:26: attempt to call method 'PlayerLogStr' (a nil value)
  1. CCommand - addons/evolve/lua/ev_plugins/sv_consolecommands.lua:26
   2. unknown - addons/evolve/lua/ev_plugins/sv_consolecommands.lua:43
    3. unknown - lua/includes/modules/concommand.lua:54"

**Comment by Xandaros** [comment]
Looks like you didn't install von properly. I should probably write a tutorial...
Download evolve with "git clone --recursive", instead of just "git clone".
And whenever you do a "git pull" to update, also do a "git submodule update --remote"

**Comment by doxlulzem** [comment]
It works a treat now! Thanks for your help!
