### ISSUE TITLE
Admins banning themselves?

### ISSUE THREAD

**Issue by TheBreakerPanel** [Xandaros/evolve#126]
Okay i have a problem with some of my admins being being smart. They figured out they could ban themselves. Is there any way i can modify the ban plugin for evolve to make it so people can't ban themselves.

Thanks!

**Comment by awilliamson** [comment]
Natural selection.

**Comment by Xandaros** [comment]
Wow...
Well, it's not a pretty mod, but it'll work: In [Line 39] of lua/ev_plugins/sh_ban.lua add:
`if pl == ply then return end`

Haven't tested it, but it should work.

[Line 39]: https://github.com/Xandaros/evolve/blob/master/lua/ev_plugins/sh_ban.lua#L39

**Comment by TheBreakerPanel** [comment]
Thanks it worked! but is there a way to make it say something like "Nice
Try" or "Did you mean yourself?" (Similar to entering !ban *)

TehBreakerPanel
