### ISSUE TITLE
Korean

### ISSUE THREAD

**Issue by dohe916** [Xandaros/evolve#128]
Hello. I am Korean. So.....I can't speak English well.......

1. Open console
2. Type 'bind t +ev_menu'
3. Setting.......
4. Press Y(chat)
5. Type Korean
6. Error!!!!

Umm.....when I speak Korean, Garry's Mod.....out.

Are you understand????
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
Korean version

안녕하세요. 저는 한국인입니다.
제가 한국인이기 때문에 이해를 못할수도 있습니다.
설명을 시작하겠습니다.

1. Open console
2. Type bind t +ev_menu
3. 설정
4. 채팅창 열기
5. 한국어 입력
6. 게리모드의 비정상적 종료

Please translate.

Simple version
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
I can't speak Korean.

**Comment by Xandaros** [comment]
I can confirm that korean doesn't work for me and neither does japanese.
However, I'm sure it used to work, so this is strange.
I'm not getting any errors, though - it's just missing the characters and showing them as boxes.

Whatever the case, this is not an evolve problem, as the vanilla gmod chat behaves the same way.
