### ISSUE TITLE
Needs Loggging

### ISSUE THREAD

**Issue by jonfrog** [Xandaros/evolve#133]
It is extremely hard to have an admin on 24/7 meaning owners and staff alike need some system to be able to look back on the commands used and chat said. That would be a great feature to have, but it's just a suggestion.

**Comment by naclark46168** [comment]
Normally, there is logs that come with your server, if you need help
finding those logs, email me back

On Wed, Apr 15, 2015 at 10:56 AM, jonfrog <notifications@github.com> wrote:

> It is extremely hard to have an admin on 24/7 meaning owners and staff
> alike need some system to be able to look back on the commands used and
> chat said. That would be a great feature to have, but it's just a
> suggestion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Xandaros/evolve/issues/133>.
>



-- 
Nicholas

**Comment by jonfrog** [comment]
Ah. I will look for those. thank you.
