### ISSUE TITLE
Evolve doesn't work.... at all

### ISSUE THREAD

**Issue by appledevdude** [Xandaros/evolve#134]
i started a brand new server, didn't add anything BUT evolve, and it gives me errors every time i do a command in chat, or spawn in:

Hook 'PlayerSpawn' in plugin 'Player Info' failed with error:

Hook 'PlayerSay' in plugin 'Chat Commands' failed with error:

**Comment by Xandaros** [comment]
Posting actual error messages would probably be helpful...

Most likely you didn't install it correctly, see #124
