### ISSUE TITLE
Can't open menu

### ISSUE THREAD

**Issue by Burns10** [Xandaros/evolve#136]
I used the "bind c +ev_menu" command, but it's not working

**Comment by Xandaros** [comment]
Well, I don't suggest binding it to c, since the context menu is already bound to that.
I'll take a look at it later, though. It should work, even if you use c as the key.

**Comment by naclark46168** [comment]
The button I use is f6 so in console, put bind f6 +ev_menu

**Comment by Burns10** [comment]
Didn't work

**Comment by naclark46168** [comment]
Hmm, I'll re download evolve on my server to recheck

**Comment by Burns10** [comment]
It seems to be loading
=====================================================
 Evolve 1.0 by Overv succesfully started clientside.
=====================================================
But then I see this
Unknown command: vermilion_menu

**Comment by Xandaros** [comment]
Just tried it - works fine for me
