### ISSUE TITLE
First time using evolve.. not working at all..

### ISSUE THREAD

**Issue by Sarms555** [Xandaros/evolve#137]
Ok, so I installed evolve admin mod for Garry's Mod through a zip file using this tutorial:
https://github.com/Xandaros/evolve
Afterwards, I ran my server to try it out.
For some reason it's as if my whole server is broken because of evolve, I no longer spawn with a physgun, or any tools at all, when I kill my character and where it's supposed to show my dead body it shows nothing, and whenever I spawn in, I get the error: 
Hook 'PlayerSpawn' in plugin 'Player Info' failed with error:
Screenshots of what console shows will be attracted.
So, is evolve broken? Am I using it wrong? Or did I download it incorrectly.
Thank you for any help you provide me with in advance.

 The Image:
![e](https://cloud.githubusercontent.com/assets/13081104/8394054/1080bc72-1cf6-11e5-81b6-229198f60c2d.PNG)

**Comment by Xandaros** [comment]
Did you properly install vON?

**Comment by Sarms555** [comment]
I believe so, this is how it goes
under my server folder --> garrysmod ---> addons ---> evolve-master ---> lua ---> includes ---> ev_von ---> and that's where I placed the folder vON-master.

Image 2:
![pic2](https://cloud.githubusercontent.com/assets/13081104/8394090/3d7ab36c-1cf7-11e5-9f17-dfbeb1bb9b71.PNG)

**Comment by Xandaros** [comment]
The vON-master folder probably contains a von.lua - that needs to go into ev_von directly.
The tutorial actually says `Make sure that the ev_von folder contains a file called "von.lua".` :)

addons/evolve/lua/includes/ev_von/von.lua

**Comment by Sarms555** [comment]
It works! Sorry I missed that in the tutorial, thank you so much! 
I really appreciate the quality in your replies, the detail really helps, not to mention the speed!
I thought I would have to wait days before getting a reply, but this literally took a blink of an eye and it's working wonderfully! Thank you SO much! :+1:  :D

**Comment by Xandaros** [comment]
Why would it take days? I usually respond as soon as I see it and thanks to [Github Notify](https://github.com/Xandaros/GithubNotify) (Shameless self-promotion) that is almost instant :P

I will leave this issue open, though - as the tutorial seems to contradict itself at that point.
