### ISSUE TITLE
Privileges: items and entities are disabled by default

### ISSUE THREAD

**Issue by oldmud0** [Xandaros/evolve#145]
Every time I add something to my server, I have to manually allow all of the new items that the addon has, for each group. This gets annoyingly repetitive.

**Comment by Xandaros** [comment]
True.
However, this is intended behaviour. I don't expect you to add new addons all the time and if you add something dangerous, I'd rather it be disallowed for everyone by default. (Lest you forget to disallow it manually. If you for get to allow it, no harm is done.)

**Comment by oldmud0** [comment]
Any shortcut for allowing an item for a group as well as higher-ranking groups?
