### ISSUE TITLE
Setting Ranks

### ISSUE THREAD

**Issue by Rorky** [Xandaros/evolve#146]
https://gyazo.com/669f6c9ba226cc97c8c04d8daa625da5

When ever I attempt to set the rank of my self it gives me that errors (I've installed everything and put the files in the correct area)

**Comment by Xandaros** [comment]
Looks to me like that's just a secondary symptom.
Do you get any other error messages? In particular when starting up the server?

**Comment by Rorky** [comment]
https://gyazo.com/9181f0b91087a07aaa5733de83714654
https://gyazo.com/355de6200b00f1d4b8462ed05193148d only errors

**Comment by Xandaros** [comment]
Despite saying you installed it correctly, that error message says otherwise.
Make sure the von.lua is in its appropriate location.

**Comment by Rorky** [comment]
evolve-master>lua>includes>von-master i put it in there

**Comment by Xandaros** [comment]
From the readme:
> Then, download the vON zip file and unzip the "von.lua" it into addons/evolve/includes/ev_von. Make sure that the ev_von folder contains a file called "von.lua".

**Comment by Rorky** [comment]
I figured out the problem thanks Xandaros
