### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by Rorky** [Xandaros/evolve#147]
I was wondering if there was a way to change the scoreboard to the one I am using instead of the Evolve one?

**Comment by MaZyGer** [comment]
Almost all changes are made in the plugins folder. If you want use your custom scoreboard so you have to remove the plugin named something like sh_scoreboard.lua or customize it and use your edition. You can rename .lua to .backup or something to "disable" it.

**Comment by Xandaros** [comment]
As @MaZyGer said, remove `lua/ev_plugins/sh_scoreboard.lua` and you should be good.
