### ISSUE TITLE
Issues with certain gamemode 

### ISSUE THREAD

**Issue by Blackheart304** [Xandaros/evolve#148]
Im having a particular issue with darkrp, Where the chat does not show /ooc only my rank anybody know how to fix this ?

**Comment by Xandaros** [comment]
Go to `addons/evolve/lua/ev_plugins` and delete the file called `sh_rankcolors.lua`.
That should disable most of evolve's chat functionality.

If you prefer to have evolve's chat over your gamemode's, you have to disable it there. In that case, I'm afraid I can't help you, as I'm not familiar with any gamemodes besides sandbox.
