### ISSUE TITLE
Priveleges not saving

### ISSUE THREAD

**Issue by PonyTerrance** [Xandaros/evolve#149]
So I have +ev_menu bound to N. I hold down N, go to the rank I wish to modify, give the permissions that I want the rank to be able to access, close the menu, and apparently its not saving the commands. 

When I rank myself to a rank, E.g super admin and use a command. For example; noclip. The following happens in console:

http://puu.sh/oQwuM/74faf42c43.png

And the following happens in chat:

http://puu.sh/oQwwY/f93e7aec13.jpg

**Comment by Xandaros** [comment]
Probably a duplicate of #124

**Comment by PonyTerrance** [comment]
Not a duplicate. Installed through git and downloading and manually installing vON.

http://puu.sh/oRy4C/b56f4744ed.png

I'm getting this when assigning permissions to ranks. E.g superadmin, or any freshly created rank. This is a clean install of evolve on a clean install of a listen server. Evolve is the only addon

**Comment by PonyTerrance** [comment]
Solved ~~ I deleted all the files from within garrysmod/data/evolve: http://puu.sh/oSCLI/20d8606787.png

Able to set permissions up again. Still not sure what triggered the files to F*** up

**Comment by Xandaros** [comment]
Interesting... @vercas hasn't updated vON in a long time, so it wasn't caused by an update.
I've never had any issues with corruption myself, but I haven't played in ages...

Anyway, glad you solved the problem. I guess corrupted data files can cause similar issues to non-installed vON :D

**Comment by vercas** [comment]
I'd be surprised if vON did anything to corrupt the data. Nobody has reported any corruption before, and it is being heavily used for years.  
It would've been useful to see those files before you deleted them.
