### ISSUE TITLE
Cant give myself owner

### ISSUE THREAD

**Issue by JohannesNeo** [Xandaros/evolve#154]
unknow ranl´k specified

**Comment by Xandaros** [comment]
I get the feeling you simply misspellt "owner"...

**Comment by JohannesNeo** [comment]
i wrote "owner" ev rank JohannesNeo owner

**Comment by jonfrog** [comment]
If you're doing it via the in-game client be sure to use rcon ev rank (name) owner after setting "rcon_password (password)" in client console.
