### ISSUE TITLE
Problem with Evolve Chat tags

### ISSUE THREAD

**Issue by bsharpie** [Xandaros/evolve#157]
Okay so I didnt know how else to get a hold of you but I have the base Darkrp gamemode atm placed evolve into the server and any time you try and talk into ooc or advert it says the usergroups rank instead so it gets a little difficult telling RP talk from OOC chat all i wanted to know was how to delete Chat tags in Evolve

**Comment by bsharpie** [comment]
Nvm I figured it out

**Comment by Xandaros** [comment]
Well, this IS how you get hold of me regarding evolve issues :)

This particular one has a bunch of issues already, though.
Maybe I should make it a bit clearer that evolve is meant for sandbox and that you're on your own if you want to get it to work on other gamemodes.

Just deleting plugins you don't want is a fairly standard operation, even on sandbox, though.
