### ISSUE TITLE
EV_IsUserGroup not working

### ISSUE THREAD

**Issue by captain1242** [Xandaros/evolve#161]
Hi,

I am building a script which needs the ability to read and give ranks but when I use 
ply:EV_IsUserGroup( rank ) it returns attempt to call method 'EV_IsUserGroup' (a nil value) maybe the function is not working of the wiki is outdated idk i just wanted to inform you.

**Comment by Xandaros** [comment]
Was evolve loaded properly? Do other such functions work?

Cause it does seem to exist: https://github.com/Xandaros/evolve/blob/master/lua/ev_framework.lua#L597

**Comment by captain1242** [comment]
Yep. Ty but you should update the wiki

**Comment by Xandaros** [comment]
Well, it _is_ a wiki :P
I updated it, though.
