### ISSUE TITLE
How to use sandbox menu?

### ISSUE THREAD

**Issue by SomeGuyOnGit** [Xandaros/evolve#167]
I cannot seem to find the command to open the sandbox menu. What is it?

**Comment by Jcdiem** [comment]
You need to bind a key to +ev_menu in the console.

Example: bind t "+ev_menu"  Would be a full command.

**Comment by SomeGuyOnGit** [comment]
I mean like this menu ( https://i.imgur.com/DPoG9Wn.png )

Since on the ranks tab I have the option to give people the option to give people the sandbox menu ( https://i.imgur.com/ZHtjZxR.png )

**Comment by Xandaros** [comment]
Uhm... you press Q?

**Comment by SomeGuyOnGit** [comment]
Yes usually, but the gamemode I am using has an inventory already made. What I am asking is if there is a command such as "+ev_sandbox" or something similar to open it for gamemodes that use Q for something else.

**Comment by nodgear** [comment]
Then your gamemode is not derived from sandbox, you can't open the spawmenu from a gamemode not derived form sandbox.
And yes, i know you're using santosrp

**Comment by Xandaros** [comment]
Sounds like the gamemode is the problem and not evolve, so I'm going to close this.

Evolve is only meant for sandbox servers - if another gamemode prevents evolve from working correctly, it is not considered a bug.
That said, it looks like your issues has nothing to do with evolve at all, so I'm not sure why you are even here.
