### ISSUE TITLE
Evolve is not working correctly on CentOS 7

### ISSUE THREAD

**Issue by Dovahkiin-Warrior** [Xandaros/evolve#170]
Using Evolve on CentOS 7, von.lua cannot be loaded from addons/evolve-master/lua/includes/ev_von/von.lua

Me being a programmer, I changed 
include( "../../includes/ev_von/von.lua")

to

include( "von.lua")

And then placed von.lua in addons/evolve-master/lua and it worked. Why do I have to change that in order to load von correctly?

**Comment by marcelgroeneveld** [comment]
https://images.mgroeneveld.nl/images/7a4dd2f5.png
Having this issue aswell on a Windows system aswell. It has something to do with case sensitive folders as the autorun looks in the ev_v**ON** folder with capital ON, however this folder by default is in full lowercase.

For the people who don't understand how to fix this, go to evolve/lua/autorun/server/ev_autorun.lua and on line 17 change this:
`include( "../../includes/ev_vON/von.lua")`
to this:
`include( "../../includes/ev_v**on**/von.lua")`

**Comment by Dovahkiin-Warrior** [comment]
Resolved. Thank you.
