### ISSUE TITLE
attempt to call method 'log'

### ISSUE THREAD

**Issue by YohSambre** [Xandaros/evolve#179]
Hello, after the installation I have an error on my local server: 

https://zupimages.net/up/22/05/4b87.png

I just got this error after installing evolve I absolutely did not configure or touch anything

**Comment by Xandaros** [comment]
Make sure vON is installed correctly. This usually happens if vON fails to load.

**Comment by YohSambre** [comment]
> Make sure vON is installed correctly. This usually happens if vON fails to load.

indeed I had forgotten this step, thank you ;)
